title: Breadcrumbs
author: Rohit
description: A trail of notes from learning in public.
baseurl: ""
url: "https://ganeshrohit.github.io"
github_username: ganeshrohit

theme: minima

minima:
  skin: dark

plugins:
  - jekyll-feed

show_excerpts: true
